package models;
// Generated 31/10/2017 10:07:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private String nombre;
     private String descripcion;
     private int valor;
     private Set productosCotizacioneses = new HashSet(0);

    public Productos() {
    }

	
    public Productos(String nombre, String descripcion, int valor) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.valor = valor;
    }
    public Productos(String nombre, String descripcion, int valor, Set productosCotizacioneses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.valor = valor;
       this.productosCotizacioneses = productosCotizacioneses;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public Set getProductosCotizacioneses() {
        return this.productosCotizacioneses;
    }
    
    public void setProductosCotizacioneses(Set productosCotizacioneses) {
        this.productosCotizacioneses = productosCotizacioneses;
    }




}


