package models;
// Generated 31/10/2017 10:07:07 AM by Hibernate Tools 4.3.1



/**
 * ProductosCotizaciones generated by hbm2java
 */
public class ProductosCotizaciones  implements java.io.Serializable {


     private Integer idProductoCotizacion;
     private Cotizaciones cotizaciones;
     private Productos productos;
     private int valor;
     private short cantidad;

    public ProductosCotizaciones() {
    }

    public ProductosCotizaciones(Cotizaciones cotizaciones, Productos productos, int valor, short cantidad) {
       this.cotizaciones = cotizaciones;
       this.productos = productos;
       this.valor = valor;
       this.cantidad = cantidad;
    }
   
    public Integer getIdProductoCotizacion() {
        return this.idProductoCotizacion;
    }
    
    public void setIdProductoCotizacion(Integer idProductoCotizacion) {
        this.idProductoCotizacion = idProductoCotizacion;
    }
    public Cotizaciones getCotizaciones() {
        return this.cotizaciones;
    }
    
    public void setCotizaciones(Cotizaciones cotizaciones) {
        this.cotizaciones = cotizaciones;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public short getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(short cantidad) {
        this.cantidad = cantidad;
    }




}


